version: 2.1
jobs:
  build:
    docker:
      - image: php:7.4
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: composer install
      - run:
          name: Run PHPUnit Tests
          command: vendor/bin/phpunit